### PR TITLE
Support startAfter for firebase query

### PR DESCRIPTION
**Pull request by lejard-h**

### CODE REVIEW

**Comment by lejard-h** [comment]
ping @johnpryan

**Review by johnpryan — APPROVED** [review]

**Comment by johnpryan** [comment]
@lejard-h merged and published here: https://github.com/johnpryan/crossfire/pulls?q=is%3Apr+is%3Aclosed

**Comment by lejard-h** [comment]
Thanks, should I create PR on you repo ?

**Comment by johnpryan** [comment]
nope it's published to pub already

**Comment by lejard-h** [comment]
Sorry I mean #7 and #6

**Comment by johnpryan** [comment]
There's a better chance I'll get notifications for PRs there since I'm not a part of this organization

**Pull request merged**
